use std::fmt;

#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub enum Tag {
    TY,
    A1, // ListType
    A2, // ListType
    A3, // ListType
    A4, // ListType
    AB,
    AD,
    AN,
    AU, // ListType
    C1,
    C2,
    C3,
    C4,
    C5,
    C6,
    C7,
    C8,
    CA,
    CN,
    CY,
    DA,
    DB,
    DO,
    DP,
    ET,
    EP,
    ID,
    IS,
    J2,
    JA,
    JF,
    JO,
    KW, // ListType
    L1,
    L2,
    L4,
    LA,
    LB,
    M1,
    M3,
    N1, // ListType
    N2,
    NV,
    OP,
    PB,
    PY,
    RI,
    RN,
    RP,
    SE,
    SN,
    SP,
    ST,
    T1,
    T2,
    T3,
    TA,
    TI,
    TT,
    UR, // ListType
    VL,
    Y1,
    Y2,
    ER,
    UK,
}

impl fmt::Display for Tag {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Tag::TY => "type_of_reference",
                Tag::A1 => "first_authors",
                Tag::A2 => "secondary_authors",
                Tag::A3 => "tertiary_authors",
                Tag::A4 => "subsidiary_authors",
                Tag::AB => "abstract",
                Tag::AD => "author_address",
                Tag::AN => "accession_number",
                Tag::AU => "authors",
                Tag::C1 => "custom1",
                Tag::C2 => "custom2",
                Tag::C3 => "custom3",
                Tag::C4 => "custom4",
                Tag::C5 => "custom5",
                Tag::C6 => "custom6",
                Tag::C7 => "custom7",
                Tag::C8 => "custom8",
                Tag::CA => "caption",
                Tag::CN => "call_number",
                Tag::CY => "place_published",
                Tag::DA => "date",
                Tag::DB => "name_of_database",
                Tag::DO => "doi",
                Tag::DP => "database_provider",
                Tag::ET => "edition",
                Tag::EP => "end_page",
                Tag::ID => "id",
                Tag::IS => "number",
                Tag::J2 => "alternate_title1",
                Tag::JA => "alternate_title2",
                Tag::JF => "alternate_title3",
                Tag::JO => "journal_name",
                Tag::KW => "keywords",
                Tag::L1 => "file_attachments1",
                Tag::L2 => "file_attachments2",
                Tag::L4 => "figure",
                Tag::LA => "language",
                Tag::LB => "label",
                Tag::M1 => "note",
                Tag::M3 => "type_of_work",
                Tag::N1 => "notes",
                Tag::N2 => "notes_abstract",
                Tag::NV => "number_of_volumes",
                Tag::OP => "original_publication",
                Tag::PB => "publisher",
                Tag::PY => "year",
                Tag::RI => "reviewed_item",
                Tag::RN => "research_notes",
                Tag::RP => "reprint_edition",
                Tag::SE => "section",
                Tag::SN => "issn",
                Tag::SP => "start_page",
                Tag::ST => "short_title",
                Tag::T1 => "primary_title",
                Tag::T2 => "secondary_title",
                Tag::T3 => "tertiary_title",
                Tag::TA => "translated_author",
                Tag::TI => "title",
                Tag::TT => "translated_title",
                Tag::UR => "urls",
                Tag::VL => "volume",
                Tag::Y1 => "publication_year",
                Tag::Y2 => "access_date",
                Tag::ER => "end_of_reference",
                Tag::UK => "unknown_tag",
            }
        )
    }
}
