name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Create Python virtual environment
      run: python -m venv .venv
    - name: Activate Python virtual environment
      run: source .venv/bin/activate
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install synergy-dataset asreview-datatools pytest pytest-benchmark maturin
    - name: Package and Install with Maturin
      run: |
        source .venv/bin/activate
        maturin develop --release
    - name: Run synergy get
      run: |
        source .venv/bin/activate
        synergy get -d Appenzeller-Herzog_2019 -l -o benches/files
    - name: Convert data
      run: |
        source .venv/bin/activate
        asreview data convert ./benches/files/Appenzeller-Herzog_2019.csv ./benches/files/Appenzeller-Herzog_2019.ris
    - name: Check
      uses: actions-rs/cargo@v1
      with:
        command: check
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
    - name: Run Rust benchmarks
      run: cargo bench
    - name: Run Python benchmarks
      run: |
        source .venv/bin/activate
        pytest --benchmark-min-rounds=10 benches/python_bench.py
